# Generated by Django 2.2.1 on 2019-05-06 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Distric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distric_canton', to='Province.Canton', to_field='name')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distric_province', to='Province.Canton')),
            ],
        ),
    ]
