# Generated by Django 2.2.1 on 2019-05-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Province', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canton',
            name='province',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='distric',
            name='canton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Province.Canton'),
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
